# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['title'], 'verbose_name': 'Fotos', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['title'], 'verbose_name': 'Descricao/Fotos', 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='quemsomos',
            options={'ordering': ['title'], 'verbose_name': 'Descricao/Foto', 'verbose_name_plural': 'Quem Somos'},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['title'], 'verbose_name': 'Descricao', 'verbose_name_plural': 'Servicos'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quemsomos',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='logos',
            field=models.ImageField(blank=True, null=True, upload_to='midioa/clientes'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='midia/portfolio'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='midia/quemsomos'),
        ),
    ]
