# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190509_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['titulo'], 'verbose_name': 'Fotos', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['titulo'], 'verbose_name': 'Descricao/Fotos', 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='quemsomos',
            options={'ordering': ['titulo'], 'verbose_name': 'Descricao/Foto', 'verbose_name_plural': 'Quem Somos'},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['titulo'], 'verbose_name': 'Descricao', 'verbose_name_plural': 'Servicos'},
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='quemsomos',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='logos',
            field=models.ImageField(blank=True, null=True, upload_to='website/midia/clientes'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/midia/portfolio'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='website/midia/quemsomos'),
        ),
    ]
