# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-11 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190509_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='logos',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='fullinfo',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='quemsomos',
            name='text',
        ),
        migrations.AddField(
            model_name='quemsomos',
            name='texto',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
