# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-12 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190511_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='imgdesc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='breveinfo',
            field=models.CharField(max_length=200),
        ),
    ]
