# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-14 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190512_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
