# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-17 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190514_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='midia/portfolio'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='quemsomos/'),
        ),
    ]
