# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-20 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190517_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='breveinfo',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='info',
        ),
        migrations.AddField(
            model_name='servicos',
            name='breveinfo1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='breveinfo2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='breveinfo3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='breveinfo4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='info1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='info2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='info3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='info4',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
