# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-21 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190521_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['titulo'], 'verbose_name': 'Descricao', 'verbose_name_plural': 'Servicos'},
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='breveinfo1',
            new_name='breveinfo',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='info1',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='titulo1',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='breveinfo2',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='breveinfo3',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='breveinfo4',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='info2',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='info3',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='info4',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='titulo2',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='titulo3',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='titulo4',
        ),
    ]
