# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-22 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190522_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name': 'Descricao', 'verbose_name_plural': 'Servicos'},
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='breveinfo',
            new_name='breveinfo1',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='info',
            new_name='breveinfo2',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='imagem',
            new_name='imagem1',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='titulo',
            new_name='titulo1',
        ),
        migrations.AddField(
            model_name='servicos',
            name='breveinfo3',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='breveinfo4',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='info1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='info2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='info3',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='info4',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='titulo2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='titulo3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicos',
            name='titulo4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
